###################################
# DKIM Configuration file
###################################
# Edit this file to add more signing domains and their selector.

[base]
# If these are present, we'll use hashicorp vault instead of reading from disk
#vault_mount = "secret"
#vault_path_prefix = "dkim/"

# To do double or triple signing, add each additional
# signature name to this list and see the `signature."MyESPName"`
# block below
#additional_signatures = ["MyESPName"]
#additional_signatures = []

# Default selector to assume if the domain/signature block
# doesn't specify one
  selector = 'defaultdk'

# The default set of headers to sign if otherwise unspecified
  headers = [ "From", "To", "Subject", "Date", "MIME-Version", "Content-Type", "Sender" ]
  algo = 'sha256'


#[domain.'kdev2.aasland.com']
#  selector = 'edtest'
#  algo = 'ed25519'
#  headers = [ 'From', 'To', 'Subject', 'Date', 'MIME-Version' ]
#  filename = "/opt/kumomta/etc/dkim/kdev2.aasland.com/id_ed25519.key"
#  policy = "SignAlways"

[domain.'demo2.kumomta.com']
#  selector = 'dkimselector'
#  algo = 'sha256'
#  headers = [ 'From', 'To', 'Subject', 'Date', 'MIME-Version' ]
#  filename = "/var/customers/keys.key"
  policy = "SignAlways"
#  policy = "SignOnlyIfInDNS"


[domain.'mx-sink.wezfurlong.org']
  selector = 'dkimselector'
  algo = 'sha256'
  headers = [ 'From', 'To', 'Subject', 'Date', 'MIME-Version' ]
  filename = "/opt/kumomta/etc/dkim/kdev2.aasland.com/dkimselector.key"
  policy = "SignAlways"
#  policy = "SignOnlyIfInDNS"



## Domain blocks match based on the sender domain of the
## incoming message
#[domain."example.com"]
#  selector = 'dkim1024'
#  headers = ["From", "To", "Subject", "Date", "MIME-Version", "Content-Type", "Sender"]
#  algo = "sha256" # or "ed25519". Omit to use the default of "sha256"
#
## optional overridden filename.
## Default is "/opt/kumomta/etc/dkim/DOMAIN/SELECTOR.key"
#  filename = "/full/path/to/key."
#
## TODO: reception-time policy for signing based on DNS.
##policy = "TempFailIfNotInDNS" # Reject
##policy = "SignAlways"         # Sign and relay
##policy = "SignOnlyIfInDNS"    # Don't sign. Allow fallback to additional_signatures
#
## The signature block is independent of the sender domain.
## They are consulted based on the value of `base.additional_signatures`
## above.
## In addition to the same values that are found in the `domain` block,
## the following keys are supported
#
#
#[signature."MyESPName"]
## Policy is interpreted differently for these
##policy = "Always" # Always add this signature
#  policy = "OnlyIfMissingDomainBlock" # Use this as a fallback
#
## specifies the signing domain for this signature block
#  domain = "myesp.com"

                                                       
                                                                                   
