
[base]

# Default selector to assume if the domain/signature block doesn't specify one
selector = 's1024'

# The default set of headers to sign if otherwise unspecified
# This reccommended set comes from section 5.4.1 of RFC 6376
# See https://datatracker.ietf.org/doc/html/rfc6376#section-5.4
headers = ['From', 'Reply-To', 'Subject', 'Date', 'To', 'List-Unsubscribe']

# Domain blocks match based on the sender domain of the
# incoming message
#[domain.'DOMAIN']
#selector = 'SELECTOR'
#headers = ['From', 'To', 'Subject' ]
#algo = 'sha256' 
#
# optional overridden filename.
# Default is '/opt/kumomta/etc/dkim/DOMAIN/SELECTOR.key'
#filename = '/opt/kumomta/etc/dkim/DOMAIN/SELECTOR.key'

policy = 'Always'


#[domain.'catchmail.puresendaws.com']
# selector = "s1024"
 



