# Egress Sources and Pools
# TOML version:

# Pool Definitions
[pool.'priority']
[pool.'priority'.'tomtest']

[pool.'default']
[pool.'default'.'tomtest']
#[pool.'default'.'tomtest-pub']

[pool.'pool-0']
[pool.'pool-0'.'tomtest']


[pool.'via_routes']
[pool.'via_routes'.'tomtest']

# Egress IP Definitions

[source.'tomtest']
  source_address = '172.31.9.228'
  ehlo_domain = 'demo2.kumomta.com'

#[source.'tomtest-pub']
#  source_address = '52.156.138.16'
#  ehlo_domain = 'kdev2.mydomain.com'




