# Egress Sources and Pools
# TOML version:

# Pool Definitions
[pool.'priority']
[pool.'priority'.'tomtest']

[pool.'default']
[pool.'default'.'tomtest']

[pool.'pool-0']
[pool.'pool-0'.'tomtest']


[pool.'via_routes']
[pool.'via_routes'.'tomtest']

# Egress IP Definitions

[source.'tomtest']
  source_address = '172.31.29.222'
  ehlo_domain = 'demo2.kumomta.com'





