# Listener Domains Configuration
# Set here how domains should behave

["*"]
  log_arf = true
  log_oob = true
  relay_to = false



["demo.kumomta.com"]
# relay to anywhere, so long as the sender domain is auth-send.example.com
# and the connected peer has authenticated as any of the authorization identities
# listed below using SMTP AUTH
relay_from_authz = [ 'demo', 'myuser' ]


