#############################################
## KumoMTA vars for config                 ##
#############################################

[vars]
  Message_Expiration = '4 hours'
  ehlo_banner = "KumoMTA DevTest sample"
  Relay_Hosts = "'127.0.0.1/32'"
  Prohibited_Hosts = "'127.0.0.0/8'"
  Hostname = "stolen.kumomta.com"
  Connection_Timeout = 5
  Banner_Timeout = 1

