# Provider syntax sample file


[provider.'yahoo']
match=[
{MXSuffix=".geocities.com"},
{MXSuffix=".kimo.com"},
{MXSuffix=".maktoob.com"},
{MXSuffix=".oddpost.com"},
{MXSuffix=".yahoo.at"},
{MXSuffix=".yahoo.be"},
{MXSuffix=".yahoo.bg"},
{MXSuffix=".yahoo.ca"},
{MXSuffix=".yahoo.cl"},
{MXSuffix=".yahoo.co.hu"},
{MXSuffix=".yahoo.co.id"},
{MXSuffix=".yahoo.co.il"},
{MXSuffix=".yahoo.co.in"},
{MXSuffix=".yahoo.co.kr"},
{MXSuffix=".yahoo.co.nz"},
{MXSuffix=".yahoo.co.th"},
{MXSuffix=".yahoo.co.uk"},
{MXSuffix=".yahoo.co.za"},
{MXSuffix=".yahoo.com"},
{MXSuffix=".yahoo.com.ar"},
{MXSuffix=".yahoo.com.au"},
{MXSuffix=".yahoo.com.br"},
{MXSuffix=".yahoo.com.cn"},
{MXSuffix=".yahoo.com.co"},
{MXSuffix=".yahoo.com.hk"},
{MXSuffix=".yahoo.com.hr"},
{MXSuffix=".yahoo.com.mx"},
{MXSuffix=".yahoo.com.my"},
{MXSuffix=".yahoo.com.pe"},
{MXSuffix=".yahoo.com.ph"},
{MXSuffix=".yahoo.com.sg"},
{MXSuffix=".yahoo.com.tr"},
{MXSuffix=".yahoo.com.tw"},
{MXSuffix=".yahoo.com.ua"},
{MXSuffix=".yahoo.com.ve"},
{MXSuffix=".yahoo.com.vn"},
{MXSuffix=".yahoo.cz"},
{MXSuffix=".yahoo.de"},
{MXSuffix=".yahoo.dk"},
{MXSuffix=".yahoo.ee"},
{MXSuffix=".yahoo.es"},
{MXSuffix=".yahoo.fi"},
{MXSuffix=".yahoo.fr"},
{MXSuffix=".yahoo.gr"},
{MXSuffix=".yahoo.hr"},
{MXSuffix=".yahoo.hu"},
{MXSuffix=".yahoo.ie"},
{MXSuffix=".yahoo.in"},
{MXSuffix=".yahoo.it"},
{MXSuffix=".yahoo.lv"},
{MXSuffix=".yahoo.nl"},
{MXSuffix=".yahoo.no"},
{MXSuffix=".yahoo.pl"},
{MXSuffix=".yahoo.pt"},
{MXSuffix=".yahoo.ro"},
{MXSuffix=".yhoo.rs"},
{MXSuffix=".yahoo.se"},
{MXSuffix=".yahoo.si"},
{MXSuffix=".yahoo.sk"},
{MXSuffix=".yahoogroups.co.kr"},
{MXSuffix=".yahoogroups.com.cn"},
{MXSuffix=".yahoogroups.com.sg"},
{MXSuffix=".yahoogroups.com.tw"},
{MXSuffix=".yahoogrupper.dk"},
{MXSuffix=".yahoogruppi.it"},
{MXSuffix=".yahoomail.com"},
{MXSuffix=".ymail.com"},
{MXSuffix=".y7mail.com"},
{MXSuffix=".aol.com"},
{MXSuffix=".aim.com"},
{MXSuffix=".aim.net"},
{MXSuffix=".americaonline.com.mx"},
{MXSuffix=".aol.ca"},
{MXSuffix=".aol.co.uk"},
{MXSuffix=".aol.com.au"},
{MXSuffix=".aol.com.br"},
{MXSuffix=".aol.com"},
{MXSuffix=".aol.com.mx"},
{MXSuffix=".aol.de"},
{MXSuffix=".aol.es"},
{MXSuffix=".aol.fr"},
{MXSuffix=".aol.in"},
{MXSuffix=".aol.it"},
{MXSuffix=".aol.nl"},
{MXSuffix=".aol.pl"},
{MXSuffix=".aol.ru"},
{MXSuffix=".aolsouthamerica.net"},
{MXSuffix=".brazilaol.net"},
{MXSuffix=".cs.com"},
{MXSuffix=".netscape.net"},
{MXSuffix=".verizon.net"},
{MXSuffix=".verizon.com"},
{MXSuffix=".bellatlantic.net"},
{MXSuffix=".bizmailsrvcs.net"},
{MXSuffix=".gte.net"},
{MXSuffix=".managedmail.com"},
{MXSuffix=".ameritech.net"},
{MXSuffix=".att.net"},
{MXSuffix=".bellsouth.net"},
{MXSuffix=".flash.net"},
{MXSuffix=".nvbell.net"},
{MXSuffix=".pacbell.net"},
{MXSuffix=".prodigy.net"},
{MXSuffix=".sbcglobal.net"},
{MXSuffix=".snet.net"},
{MXSuffix=".swbell.net"},
{MXSuffix=".wans.net"},
{MXSuffix=".worldnet.att.net"},
{MXSuffix=".btopenworld.com"},
{MXSuffix=".mybtinternet.com"},
{MXSuffix=".talk21.com"},
{MXSuffix=".rogers.com"},
{MXSuffix=".sky.com"}
]

  max_connection_rate =  '250/s'
  connection_limit =    10
  max_deliveries_per_connection =  10



[provider.'msn']
match=[
{MXSuffix=".hotmail.com"},
{MXSuffix=".hotmail.co.uk"},
{MXSuffix=".hotmail.at"},
{MXSuffix=".hotmail.bs"},
{MXSuffix=".hotmail.ca"},
{MXSuffix=".hotmail.co.il"},
{MXSuffix=".hotmail.com.ar"},
{MXSuffix=".hotmail.com.au"},
{MXSuffix=".hotmail.com.br"},
{MXSuffix=".hotmail.com.tr"},
{MXSuffix=".hotmail.de"},
{MXSuffix=".hotmail.dk"},
{MXSuffix=".hotmail.es"},
{MXSuffix=".hotmail.fr"},
{MXSuffix=".hotmail.it"},
{MXSuffix=".hotmail.se"},
{MXSuffix=".microsoft.com"},
{MXSuffix=".live.com"},
{MXSuffix=".live.at"},
{MXSuffix=".live.ca"},
{MXSuffix=".passport.com"},
{MXSuffix=".msn.com"},
{MXSuffix=".outlook.com"},
{MXSuffix=".windowslive.com"}
]
  max_connection_rate = '200/s'
  max_deliveries_per_connection =   20


[provider.'icloud']
match=[
{MXSuffix=".icloud.com"},
{MXSuffix=".mac.com"},
{MXSuffix=".me.com"}
]
