###################################
# Aasland shaping file for in-house IPs
###################################

["default"]
  replace_base = true
  max_deliveries_per_connection = 1

#  enable_tls = 'Opportunistic'
  enable_tls = 'Disabled'
#  max_ready = 10000
  connection_limit  = 1
  prohibited_hosts = ['127.0.0.0/8']
#  max_connection_rate = '100/hour'


['utils.kumomta.com']
smtp_port = 587



[["yahoo.com".automation]]
regex = "421"
action = "Suspend"
duration = "10 minutes"

[["yahoo.com".automation]]
regex = "failure"
action = "Suspend"
duration = "10 minutes"

[["yahoo.com".automation]]
regex = "\\[TSS04\\]"
action = "Suspend"
duration = "1 hour"

[["gmail.com".automation]]
regex = "account"
action = "Suspend"
duration = "20 minutes"



