# Egress Sources and Pools
# TOML version:

# Pool Definitions
[pool.'priority']
[pool.'priority'.'tomtest']

[pool.'default']
[pool.'default'.'tomtest']

[pool.'pool-0']
[pool.'pool-0'.'tomtest']

[pool.'pool-1']
[pool.'pool-1'.'tomtest']

[pool.'ext']
[pool.'ext'.'external']

[pool.'via_routes']
[pool.'via_routes'.'tomtest']

# Egress IP Definitions

[source.'tomtest']
  source_address = '172.31.3.232'
  ehlo_domain = 'cord.kumomta.com'

[source.'external']
 socks5_proxy_server = '172.31.9.228:5000'
 socks5_proxy_source_address = '172.31.9.228'
 ehlo_domain = 'ex.cord.kumomta.com'





